TRUNCATE TABLE cryptocurrency_info;
ALTER TABLE rolenamecurrency_infouser_rolescurrency_info AUTO_INCREMENT = 1;
TRUNCATE TABLE currency_daily_price;
ALTER TABLE currency_daily_price AUTO_INCREMENT = 1;
TRUNCATE TABLE currency_interval;
ALTER TABLE currency_interval AUTO_INCREMENT = 1;
TRUNCATE TABLE tracker;
ALTER TABLE tracker AUTO_INCREMENT = 1;
TRUNCATE TABLE users;
ALTER TABLE users AUTO_INCREMENT = 1;